name: CI
on: 
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main, feature/*]
jobs:
  check-compile-flags:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build-essentials
        if: success()
        run: |
          sudo apt update
          sudo apt-get install -y gcc cmake make python3-pip

      - name: Install conan2.x
        if: success()
        run: |
          sudo pip install conan
          rm -f ~/.conan2/profiles/default
          conan profile detect
          sed -i -E 's/gnu[0-9]{2}/gnu17/g' ~/.conan2/profiles/default
          conan install . --build=missing --settings=build_type=Debug
          source ./build/Debug/generators/conanrun.sh
          conan install . --build=missing --settings=build_type=Release
          source ./build/Release/generators/conanrun.sh

      # build
      - name: Build&Tests
        if: success()
        run: |
          cmake --preset conan-debug
          cmake --build --preset conan-debug
          ./build/Debug/Tests/Tests
