name: CI
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check-compile-flags:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build-essentials
        run: |
          sudo apt update
          sudo apt-get install -y gcc cmake make python3-pip

      - name: Install conan2.x
        run: |
          pip install conan
          source ~/.profile

      - name: Install Conan profiles
        run: |
          conan profile detect
          echo \[settings\] > ~/default
          echo arch=x86_64 >> ~/default
          echo build_type=Release >> ~/default
          echo compiler=gcc >> ~/default
          echo compiler.cppstd=gnu17 >> ~/default
          echo compiler.libcxx=libstdc++ >> ~/default
          echo compiler.version=9 >> ~/default
          echo os=Linux >> ~/default

      - name: Install Conanfile.py
        run: |
          echo "pwd:"
          echo `pwd`'
          
