message(STATUS "Conan: Using CMakeDeps conandeps_legacy.cmake aggregator via include()")
message(STATUS "Conan: It is recommended to use explicit find_package() per dependency instead")

find_package(flatbuffers)
find_package(Boost)
find_package(RapidJSON)
find_package(TBB)
find_package(spdlog)
find_package(fmt)
find_package(rapidcsv)
find_package(magic_enum)
find_package(CURL)
find_package(ZLIB)
find_package(stduuid)
find_package(base64)
find_package(redis++)
find_package(GTest)

set(CONANDEPS_LEGACY  flatbuffers::flatbuffers  boost::boost  rapidjson  onetbb::onetbb  spdlog::spdlog  fmt::fmt  rapidcsv::rapidcsv  magic_enum::magic_enum  CURL::libcurl  ZLIB::ZLIB  stduuid::stduuid  aklomp::base64  redis++::redis++_static  gtest::gtest )